# Generated by Django 3.2.8 on 2022-05-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0003_auto_20220516_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.FileField(upload_to='posts/'),
        ),
    ]
