# Generated by Django 3.2.8 on 2022-05-17 13:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0004_alter_postimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(default=django.utils.timezone.now, upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
