# Generated by Django 3.2.8 on 2022-05-17 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0006_auto_20220517_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
