# Generated by Django 3.2.8 on 2022-05-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0007_delete_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stack',
        ),
    ]
