# Generated by Django 3.2.8 on 2022-05-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0009_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='intro',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='whoismari.Tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='thumbnails/'),
        ),
    ]
