# Generated by Django 3.2.8 on 2022-06-16 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0011_auto_20220616_1141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectImages',
            new_name='ProjectImage',
        ),
    ]
