# Generated by Django 3.2.8 on 2022-06-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0012_rename_projectimages_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.FileField(blank=True, upload_to='projects-thumbnails/'),
        ),
    ]
