# Generated by Django 3.2.8 on 2022-06-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0013_project_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
