# Generated by Django 3.2.8 on 2022-06-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0014_projectimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
