# Generated by Django 4.2.20 on 2026-04-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0017_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_tags',
            field=models.ManyToManyField(blank=True, related_name='cat_projects', to='whoismari.tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='stack_tags',
            field=models.ManyToManyField(blank=True, related_name='stack_projects', to='whoismari.tag'),
        ),
    ]
