# Generated by Django 4.2.20 on 2026-04-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoismari', '0018_add_project_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
